 //stuff for alarm

/*function time_to() {
var hour = document.getElementById('hour').value;
var minute = document.getElementById('minute').value;
var endstring = "" + hour + ':' + minute + ':00';
var startTime = moment().format('HH:mm:ss');
console.log("time now is: "+startTime);
console.log("endstring is: " + endstring);
var endTime= moment('' + hour + ':' + minute + ':00', 'HH:mm:ss');
console.log("endtime is: " +endTime);
var duration = moment.duration(endTime.diff(startTime));
console.log("duration is: " + duration);
var hours = duration.asHours();
var minutes = duration.asMinutes()-hours*60;
alert (hours + ' hour and '+ minutes+' minutes.');
}

function alerted() {
alert("TIME!");
}

*/

    $(document).ready(function(){
   

   $("#add").click(function(){
        console.log("add clicked");
$("#forms").show();
      });    

 });
 
function get_todos() {//retrieves todos, puts them in array
    var todos = new Array; // creating a new array which will hold the todos
    var todos_str = localStorage.getItem('todo');//using getItem method to get todos from local storage
    if (todos_str !== null) { //if there is something in the todos string, must use JSON.parse to convert array into javascript string
        todos = JSON.parse(todos_str); 
    }
    return todos; //outputs the todos string
}

function get_times() {//retrieves associated times, puts them in array
	var times = new Array;
	var times_str = localStorage.getItem('time');
	if (times_str !== null) {
		times = JSON.parse(times_str);
	}
	return times;
}
 
function add() {//adds new tasks to the todos_str array
    var task = document.getElementById('task').value; //assigns what is in the "task" field to "task" variable
    var time = document.getElementById('hour').value + ":" + document.getElementById('minute').value;
    console.log('time is: ' + time);
    if (time == 'none:none')
    {
        time ="any time";
        time_prefix = false;
    }
    var todos = get_todos(); //calls get_todos (ie: updates every time a new task is added)
    var times = get_times();
    todos.push(task); //the "push" method called on an array adds this new "task" to the array
    times.push(time);
    localStorage.setItem('todo', JSON.stringify(todos)); //stores the returned final string of all the todos (stringifies using JSON.stringify)
    localStorage.setItem('time', JSON.stringify(times));
    //time_to();
    show1(); //runs the "show" function, which updates the list of todos
    return false; //returns false to avoid further actions generated by the click event
}

 
function remove() {//removes things from the list
    var id = this.getAttribute('id'); //gets the id of whatever element of the list needs to be removed
    var todos = get_todos(); //calls the get todos again
    var times = get_times();
    todos.splice(id, 1); //splices(removes) the todo at a certain id todos.splice(index, howmany)
    times.splice(id, 1);
    localStorage.setItem('todo', JSON.stringify(todos)); //puts this new array back into a string using JSON.stringify
    localStorage.setItem('time', JSON.stringify(times));
 
    show1(); //calls the show function, to update the list
 
    return false;
}
 
function show1() {
    var todos = get_todos(); //gets the todo list
    var times = get_times(); //gets the times list
    //top bar stuff

    var today = new Date();
    var weekday = today.getDay();
    var weekday_name = new Array(7);
    weekday_name[0] =  "Sunday";
    weekday_name[1] = "Monday";
    weekday_name[2] = "Tuesday";
    weekday_name[3] = "Wednesday";
    weekday_name[4] = "Thursday";
    weekday_name[5] = "Friday";
    weekday_name[6] = "Saturday";
    var real_weekday = weekday_name[weekday];
    var num_tasks;
    if (todos.length ==1)
    {
        num_tasks = todos.length + ' task';
    }
    else
    {
        num_tasks = todos.length + ' tasks';
    }
    var html = '<h1>'+real_weekday+'</h1><p>You have ' + num_tasks + '</p>';

    document.getElementById('banner').innerHTML = html;
    var html = '<ul>';//formatting

    for(var i=0; i<todos.length; i++) {

        html += '<li><span><b>' + todos[i] + '</b> at <b>' + times[i] + '</b></span><span style = "float: right;"><button class="remove"  id="' + i  + '">x</button></span></li>'; //adding a button of class remove to all of the things on the list

    };
    html += '</ul>';
    document.getElementById('todos').innerHTML = html;//putting whatever has been assigned to html into the todos section of the page
 
    var buttons = document.getElementsByClassName('remove');//fetching all the buttons
    for (var i=0; i < buttons.length; i++) {//adds an event listener to the remove buttons
        buttons[i].addEventListener('click', remove);//connects "click" to the "remove" function (not the class)
    };

}
     var time_prefix = true;

document.getElementById('add').addEventListener('click', add); //adds an event listener to associate "click" with the "add" function when called on the add button
show1(); //calls the show function


				


